### ISSUE TITLE
[BUG]: Results are not showing when we use component inside ion-toolbar

### ISSUE THREAD

**Issue by gchokeen** [jrquick17/ionic4-auto-complete#33]
# I'm submitting a
- [ ] Bug report

## Description

    Dropdown results are hidden when use this component inside ion-toolbar 

### Version Information

```
   Ionic CLI                     : 5.2.3 
   Ionic Framework               : @ionic/angular 4.11.1
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0
```

### Browser

- [ ] Chrome - 78.0.3904.108 (Official Build) (64-bit)

**Comment by mrmikez** [comment]
I agree, same for ion-item

**Comment by jrquick17** [comment]
@mrmikez Checkout the demo, [specifically this example](https://github.com/jrquick17/ionic4-auto-complete/tree/master/demo/src/app/components/multi-function). It uses the component within `ion-item`.

**Comment by jrquick17** [comment]
@gchokeen I have not tried using within an `ion-toolbar` but I would guess that the solution used to fix `ion-item` would also work for you. It will likely involve CSS outside of this library.

**Comment by mrmikez** [comment]
> @mrmikez Checkout the demo, [specifically this example](https://github.com/jrquick17/ionic4-auto-complete/tree/master/demo/src/app/components/multi-function). It uses the component within `ion-item`.

Okay, I will check this. Thank you.

**Comment by gchokeen** [comment]
No luck yet with css solution that you showed in example, keep trying something else

**Comment by Eraldo** [comment]
I also faced this when having the component in an `ion-item`.

**Comment by jrquick17** [comment]
@Eraldo https://github.com/jrquick17/ionic4-auto-complete/issues/33#issuecomment-561697996

**Comment by Eraldo** [comment]
@jrquick17 I did see that comment, but I had a type.
^_^ Today my concentration is low it seems.

**Comment by pascalalfadian** [comment]
I had the same problem with `ion-item`.

I think the part which you need to see in example is [this style override](https://github.com/jrquick17/ionic4-auto-complete/blob/0a86a51cb6c2ceb4c3d4116886f0bfba99192bb4/demo/src/app/components/multi-function/multi-function.component.html#L8).

Setting `overflow: inherit` or `overflow:visible` in my `ion-item` solved such problem, because `ion-item` has this style `overflow: hidden` that hides the pop-up.

Didn't try for `ion-toolbar`, though.

**Comment by jrquick17** [comment]
Like @pascalalfadian said, this problem lies with how the `ion-toolbar` is rendered and the solution is not to change anything within this project so I am going to close the issue for now. If I am incorrect then feel free to reopen or submit a pull request.

I have found several people in multiple forums asking for a solution and none of the ones I have tried have worked ([example 1](https://stackoverflow.com/questions/56322782/ionic-4-how-to-overflow-div-from-ionic-header-or-toolbar) and [example 2](https://forum.ionicframework.com/t/disable-overflow-hidden-on-ion-footer-and-ion-header/103690)).

However, I have found a workaround that works well. Just remove the `ion-toolbar` completely and put the auto complete directly in the `ion-header` like so:

```
<ion-header class="ion-padding-horizontal ion-padding-vertical">
  <ion-auto-complete [dataProvider]="completeTestService"></ion-auto-complete>
</ion-header>
```

[Here is an example repository that I made for testing.](https://github.com/jrquick17/i4ac-test)

**Comment by davidecampello** [comment]
Hi! Did you find any solution with ion-toolbar?
Thanks

**Comment by dyegonery** [comment]
After a lot of debugging, I managed to solve this problem using the component inside a toolbar. 
The solution involves other package, though. I had to use shadow-dom-inject-styles to inject styles on the ion-toolbar shadow dom elements.
Here's the styles I had to add:

`const styles = `
            ion-toolbar {
                contain: none !important;
                overflow: visible !important;
            }
            .toolbar-container {
                contain: none !important;
                overflow: visible !important;
            }

            .toolbar-container .toolbar-content {
                contain: none !important;
                overflow: visible !important;
            }
        `;`
